[package]
name = "human_name"
version = "0.0.1"
authors = ["David Judd <david@academia.edu>"]

[dependencies]
itertools = "0.4.*"
unicode-segmentation = "0.1.*"
unicode-normalization = "0.1.*"
rustc-serialize = "0.3.*"
phf = "0.7.*"
phf_macros = { version = "0.7.*", git = "https://github.com/djudd/rust-phf", branch = "rustc-plugin-rename" }

[features]
default = ["name_eq_hash"]
name_eq_hash = []

[profile.release]
debug = true

[[bin]]
name = "human_name"
doc = false
