[package]
name = "human_name"
version = "0.7.2"
authors = ["David Judd <david.a.judd@gmail.com>"]
description = "A library for parsing and comparing human names"
license = "Apache-2.0"
repository = "https://github.com/djudd/human-name"
documentation = "http://djudd.github.io/human-name"

[dependencies]
itertools = "0.8"
unicode-segmentation = "1.2"
unicode-normalization = "0.1"
unidecode = "0.3"
rustc-serialize = "0.3"
phf = "0.7"
phf_macros = "0.7"
libc = "0.2"
smallvec = "0.6"
inlinable_string = "0.1"
regex = "1"
lazy_static = "1.2"

[features]
default = ["name_eq_hash"]
name_eq_hash = []

[profile.release]
debug = true
lto = true

[[bin]]
name = "human_name"
doc = false

[lib]
name = "human_name"
crate-type = ["rlib", "dylib"]
