[package]
name = "human_name"
version = "0.0.1"
authors = ["David Judd <david.a.judd@gmail.com>"]
description = "A library for parsing and comparing human names"
license = "Apache-2.0"
repository = "https://github.com/djudd/human-name"

[dependencies]
itertools = "0.4.*"
unicode-segmentation = "0.1.*"
unicode-normalization = "0.1.*"
rustc-serialize = "0.3.*"
phf = "0.7.*"
phf_macros = "0.7.*"

[features]
default = ["name_eq_hash"]
name_eq_hash = []

[profile.release]
debug = true

[[bin]]
name = "human_name"
doc = false
